### ISSUE TITLE
Skip certificate verification or pass vault cert.

### ISSUE THREAD

**Issue by raider444** [nymous/pydantic-vault#16]
Hi, is it possible to skip vault certificate verification? In hvac library you can pass verify=False or define certificate.

**Comment by nymous** [comment]
Hello @raider444, sorry for the delay!

That is indeed a cool idea! Would you be ready to submit a PR adding support for this?
Maybe adding a `vault_certificate_verify` field in the `Config` class could work, with a `None` default value, but accepting a path to a certificate or `False`, and forward it to the `hvac` calls underneath.
Should we also support an environment variable for this? I know there is already `REQUESTS_CA_BUNDLE` and `CURL_CA_BUNDLE`, but they would change `requests` behavior globally which could be too much.

**Comment by nymous** [comment]
Fixed by #24, and release in 0.8.0.
